export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';
export const COUNTER_RESET = 'COUNTER_RESET';
export const COUNTER_UPDATE_NAME = 'COUNTER_UPDATE_NAME';
export const GET_JOKE = 'GET_JOKE';